POST http://localhost:4000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImRlNDI0MWU2LWFlNzgtNGZhZC1hOTY5LWZjYmZlMmJhZTJiOCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzE2NjgwMywidXNlcl9pZCI6MTd9.8fa86j03jh9IofD-16aCQKhMt-HNtGgyKgL_ARIqtiU

{
    "username": "test2",
    "password": "test2"
}

###
POST http://localhost:4000/room
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImRlNDI0MWU2LWFlNzgtNGZhZC1hOTY5LWZjYmZlMmJhZTJiOCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzE2NjgwMywidXNlcl9pZCI6MTd9.8fa86j03jh9IofD-16aCQKhMt-HNtGgyKgL_ARIqtiU

{
    "participants": [17]
}

###
POST http://localhost:4000/user/alias/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImRlNDI0MWU2LWFlNzgtNGZhZC1hOTY5LWZjYmZlMmJhZTJiOCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzE2NjgwMywidXNlcl9pZCI6MTd9.8fa86j03jh9IofD-16aCQKhMt-HNtGgyKgL_ARIqtiU

{
    "alias": "choynee"
}

###
POST http://localhost:4000/user/password/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImRlNDI0MWU2LWFlNzgtNGZhZC1hOTY5LWZjYmZlMmJhZTJiOCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzE2NjgwMywidXNlcl9pZCI6MTd9.8fa86j03jh9IofD-16aCQKhMt-HNtGgyKgL_ARIqtiU

{
    "current_password": "test3",
    "new_password": "test2"
}

###
DELETE http://localhost:4000/user/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImRlNDI0MWU2LWFlNzgtNGZhZC1hOTY5LWZjYmZlMmJhZTJiOCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzE2NjgwMywidXNlcl9pZCI6MTd9.8fa86j03jh9IofD-16aCQKhMt-HNtGgyKgL_ARIqtiU

###
http://localhost:4000/user/info/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImRlNDI0MWU2LWFlNzgtNGZhZC1hOTY5LWZjYmZlMmJhZTJiOCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzE2NjgwMywidXNlcl9pZCI6MTd9.8fa86j03jh9IofD-16aCQKhMt-HNtGgyKgL_ARIqtiU


### 
POST http://localhost:4000/login 

{
    "username": "chyonee",
    "password": "1234"
}

###
http://localhost:4000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImRlNDI0MWU2LWFlNzgtNGZhZC1hOTY5LWZjYmZlMmJhZTJiOCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzE2NjgwMywidXNlcl9pZCI6MTd9.8fa86j03jh9IofD-16aCQKhMt-HNtGgyKgL_ARIqtiU

###
http://localhost:4000/user/room/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImRlNDI0MWU2LWFlNzgtNGZhZC1hOTY5LWZjYmZlMmJhZTJiOCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzE2NjgwMywidXNlcl9pZCI6MTd9.8fa86j03jh9IofD-16aCQKhMt-HNtGgyKgL_ARIqtiU

###
http://localhost:4000/ws/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImRlNDI0MWU2LWFlNzgtNGZhZC1hOTY5LWZjYmZlMmJhZTJiOCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzE2NjgwMywidXNlcl9pZCI6MTd9.8fa86j03jh9IofD-16aCQKhMt-HNtGgyKgL_ARIqtiU

###
http://localhost:4000/room/7/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImRlNDI0MWU2LWFlNzgtNGZhZC1hOTY5LWZjYmZlMmJhZTJiOCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzE2NjgwMywidXNlcl9pZCI6MTd9.8fa86j03jh9IofD-16aCQKhMt-HNtGgyKgL_ARIqtiU