POST http://localhost:4000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjZiYmEzY2Y5LTc4MTUtNDZiMC04ZmU2LWZmZjZhMzM4MzIyYiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzMzMTI4NiwidXNlcl9pZCI6MTd9.FABXknIMTUDsD3LTtqwdxXfV8Gpa9LXXzuvY1KG5sQw

{
    "username": "test2",
    "password": "test2"
}

###
POST http://localhost:4000/room
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjZiYmEzY2Y5LTc4MTUtNDZiMC04ZmU2LWZmZjZhMzM4MzIyYiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzMzMTI4NiwidXNlcl9pZCI6MTd9.FABXknIMTUDsD3LTtqwdxXfV8Gpa9LXXzuvY1KG5sQw

{
    "participants": [17]
}

###
POST http://localhost:4000/user/alias/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjZiYmEzY2Y5LTc4MTUtNDZiMC04ZmU2LWZmZjZhMzM4MzIyYiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzMzMTI4NiwidXNlcl9pZCI6MTd9.FABXknIMTUDsD3LTtqwdxXfV8Gpa9LXXzuvY1KG5sQw

{
    "alias": "choynee"
}

###
POST http://localhost:4000/user/password/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjZiYmEzY2Y5LTc4MTUtNDZiMC04ZmU2LWZmZjZhMzM4MzIyYiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzMzMTI4NiwidXNlcl9pZCI6MTd9.FABXknIMTUDsD3LTtqwdxXfV8Gpa9LXXzuvY1KG5sQw

{
    "current_password": "test3",
    "new_password": "test2"
}

###
DELETE http://localhost:4000/user/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjZiYmEzY2Y5LTc4MTUtNDZiMC04ZmU2LWZmZjZhMzM4MzIyYiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzMzMTI4NiwidXNlcl9pZCI6MTd9.FABXknIMTUDsD3LTtqwdxXfV8Gpa9LXXzuvY1KG5sQw

###
http://localhost:4000/user/info/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjZiYmEzY2Y5LTc4MTUtNDZiMC04ZmU2LWZmZjZhMzM4MzIyYiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzMzMTI4NiwidXNlcl9pZCI6MTd9.FABXknIMTUDsD3LTtqwdxXfV8Gpa9LXXzuvY1KG5sQw


### 
POST http://localhost:4000/login 

{
    "username": "chyonee",
    "password": "1234"
}

###
http://localhost:4000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjZiYmEzY2Y5LTc4MTUtNDZiMC04ZmU2LWZmZjZhMzM4MzIyYiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzMzMTI4NiwidXNlcl9pZCI6MTd9.FABXknIMTUDsD3LTtqwdxXfV8Gpa9LXXzuvY1KG5sQw

###
http://localhost:4000/user/room/17
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjZiYmEzY2Y5LTc4MTUtNDZiMC04ZmU2LWZmZjZhMzM4MzIyYiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzMzMTI4NiwidXNlcl9pZCI6MTd9.FABXknIMTUDsD3LTtqwdxXfV8Gpa9LXXzuvY1KG5sQw

###
http://localhost:4000/ws/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjZiYmEzY2Y5LTc4MTUtNDZiMC04ZmU2LWZmZjZhMzM4MzIyYiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzMzMTI4NiwidXNlcl9pZCI6MTd9.FABXknIMTUDsD3LTtqwdxXfV8Gpa9LXXzuvY1KG5sQw

###
http://localhost:4000/room/7/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjZiYmEzY2Y5LTc4MTUtNDZiMC04ZmU2LWZmZjZhMzM4MzIyYiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzMzMTI4NiwidXNlcl9pZCI6MTd9.FABXknIMTUDsD3LTtqwdxXfV8Gpa9LXXzuvY1KG5sQw

###
http://localhost:4000/room/7/messages 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjZiYmEzY2Y5LTc4MTUtNDZiMC04ZmU2LWZmZjZhMzM4MzIyYiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzMzMTI4NiwidXNlcl9pZCI6MTd9.FABXknIMTUDsD3LTtqwdxXfV8Gpa9LXXzuvY1KG5sQw


###
POST http://localhost:4000/message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjZiYmEzY2Y5LTc4MTUtNDZiMC04ZmU2LWZmZjZhMzM4MzIyYiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMzMzMTI4NiwidXNlcl9pZCI6MTd9.FABXknIMTUDsD3LTtqwdxXfV8Gpa9LXXzuvY1KG5sQw

{
    "message": "test",
    "roomId": "7"
}