POST http://localhost:4000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImU0YTU2YzlhLThkYWQtNDg2Zi1hNjEyLWJkOGU2OGFmN2NkZCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMjMwMzYwMSwidXNlcl9pZCI6NH0.IMQjBUUUiET_w2z3gR2_2DrcrjcBwP0KNW-sOopsRvc

{
    "username": "test2",
    "password": "test2"
}

###
POST http://localhost:4000/room
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImU0YTU2YzlhLThkYWQtNDg2Zi1hNjEyLWJkOGU2OGFmN2NkZCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMjMwMzYwMSwidXNlcl9pZCI6NH0.IMQjBUUUiET_w2z3gR2_2DrcrjcBwP0KNW-sOopsRvc

{
    "participants": [4]
}

###
POST http://localhost:4000/user/alias/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImU0YTU2YzlhLThkYWQtNDg2Zi1hNjEyLWJkOGU2OGFmN2NkZCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMjMwMzYwMSwidXNlcl9pZCI6NH0.IMQjBUUUiET_w2z3gR2_2DrcrjcBwP0KNW-sOopsRvc

{
    "alias": "choynee"
}

###
POST http://localhost:4000/user/password/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImQ2MGZkMGVlLWJiN2YtNDczNS04MTY0LTdmNzVkMDIxNGJiOCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMjMyMDM5NSwidXNlcl9pZCI6NX0.WK-cfyMAvSfxJWX0-HuarYg1bSLHSdMGfZ6gGhgrk68

{
    "current_password": "test3",
    "new_password": "test2"
}

###
DELETE http://localhost:4000/user/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6IjU4NzJmZTYxLTE1NzEtNDNhYi05NWI2LWNiMGFmM2Q0N2ZhYiIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMjMyNDAxOCwidXNlcl9pZCI6Nn0.m2j_56KTq3z6Pislz_U31xJopR1XRXFzd_OB1eXM_wQ



### 
POST http://localhost:4000/login 

{
    "username": "test2",
    "password": "test2"
}

###
http://localhost:4000/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NfdXVpZCI6ImQ2MGZkMGVlLWJiN2YtNDczNS04MTY0LTdmNzVkMDIxNGJiOCIsImF1dGhvcml6ZWQiOnRydWUsImV4cCI6MTYzMjMyMDM5NSwidXNlcl9pZCI6NX0.WK-cfyMAvSfxJWX0-HuarYg1bSLHSdMGfZ6gGhgrk68